### ISSUE TITLE
Upgrade `sbt` & `scala` to allow Scala Steward to run

### ISSUE THREAD

**Issue by rtyley** [guardian/zuora-full-export#51]
We need at least [Scala](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#scala-compatibility-table) 2.13.11 & [sbt](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#build-tool-compatibility-table) 1.9.0+ to run Scala Steward, see:

* https://github.com/guardian/maintaining-scala-projects/issues/7

Otherwise the Scala Steward run [fails](https://github.com/guardian/scala-steward-public-repos/actions/runs/11857541830/job/33046152777#step:7:2868)!

In the meantime, I've removed this repo from the Scala Steward run.

cc @AndreaDiotallevi

**Comment by AndreaDiotallevi** [comment]
This [PR](https://github.com/guardian/zuora-full-export/pull/52) should fix this.

Thanks for flagging.

**Comment by rtyley** [comment]
Thanks @AndreaDiotallevi - I can confirm that https://github.com/guardian/zuora-full-export/pull/52 has fixed the issue- I've re-added `zuora-full-export` to the Scala Steward job, the latest run [successfully](https://github.com/guardian/scala-steward-public-repos/actions/runs/11910530483) completed & updated https://github.com/guardian/zuora-full-export/pull/48.
